#OBJECT ORIENTED PROGRAMMING LANGUAGE
# COMMON TOPIC IN ALMOST ALL POPULAR PROGRAMMING LANGUAGES[C,C++,JAVA]
# WITH COMMON IDEA BUT DIFFERENT SYNTEX
# OOP IS JUST A STYLE/WAY TO WRITE A CODE
# VERY HELPFUL IN CREATING REAL WORLD PROGRAMS
# WE WILL SEE OTHER ADVANTAGES WHEN WE WILL START LEARNING OOP

# class,object,methods
l=[1,2,3,4]
l2=[2,3,4,5]
l3=['vidhi','himanshu'] #class/object
l.append(l2)  #method   